use crate::musig2::error::MuSig2Error;
use ark_ec::AffineRepr;
use ark_ff::PrimeField;
use ark_serialize::{CanonicalDeserialize, CanonicalSerialize};
use std::collections::HashMap;
use std::fmt::Debug;

/// Represents the current state of a MuSig2 signing session
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum MuSig2SessionState {
    /// Session has been initialized with participants
    Initialized,

    /// The aggregated key has been computed
    KeyAggregated,

    /// Round 1: Nonces have been generated by this signer
    NoncesGenerated,

    /// Round 1: All nonces from all signers have been collected
    NoncesCollected,

    /// Round 1: The aggregate nonce has been computed
    NonceAggregated,

    /// Round 2: Partial signature has been generated by this signer
    PartiallySignedLocal,

    /// Round 2: All partial signatures from all signers have been collected
    SignaturesCollected,

    /// Round 3: Final signature has been aggregated
    Completed,
}

/// Represents a signer's identity in the protocol
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct SignerId(pub String);

impl SignerId {
    /// Creates a new signer ID from a public key
    pub fn from_public_key<G: AffineRepr>(pk: &G) -> Result<Self, MuSig2Error> {
        let mut pk_bytes = Vec::new();
        pk.serialize_compressed(&mut pk_bytes)?;
        Ok(SignerId(format!("{:?}", pk_bytes)))
    }
}

/// Represents a hash function used in the MuSig2 protocol
pub trait MuSig2HashFunction<S: PrimeField> {
    /// Generic hash function for the MuSig2 protocol with domain separation
    ///
    /// - `domain`: A domain separation string (e.g., "aggregate", "nonce", "signature")
    /// - `data`: The data to hash
    fn hash(&self, domain: &str, data: &[&[u8]]) -> Result<S, MuSig2Error>;
}

/// MuSig2 session for a specific signing operation
#[derive(Debug, Clone)]
pub struct MuSig2Session<G, H>
where
    G: AffineRepr,
    H: MuSig2HashFunction<G::ScalarField>,
{
    /// The unique session identifier
    pub session_id: String,

    /// Current state of the session
    pub state: MuSig2SessionState,

    /// The message being signed
    pub message: Vec<u8>,

    /// Sorted list of public keys of all cosigners
    pub cosigner_public_keys: Vec<G>,

    /// Map of aggregation coefficients for each key
    pub key_aggregation_coeffs: HashMap<SignerId, G::ScalarField>,

    /// The aggregated public key for all cosigners
    pub aggregated_public_key: Option<G>,

    /// Local signer's index in the cosigners list
    pub local_signer_idx: Option<usize>,

    /// Generated secret nonces for the local signer (two nonces per MuSig2 protocol)
    pub secret_nonces: Option<(G::ScalarField, G::ScalarField)>,

    /// Public nonces from all signers (including local one)
    pub public_nonces: HashMap<SignerId, (G, G)>,

    /// Nonce aggregation coefficient (b in the MuSig2 paper)
    pub nonce_aggregation_coeff: Option<G::ScalarField>,

    /// The aggregated nonce for the signing session
    pub aggregated_nonce: Option<G>,

    /// Challenge value (c in the MuSig2 paper)
    pub challenge: Option<G::ScalarField>,

    /// Partial signatures from all signers
    pub partial_signatures: HashMap<SignerId, G::ScalarField>,

    /// Final signature (R, s) where R is the aggregated nonce and s is the aggregated signature
    pub final_signature: Option<MuSig2Signature<G>>,

    /// Hash function used for the protocol
    pub hash_function: H,
}

/// The final MuSig2 signature
#[derive(Debug, Clone, CanonicalSerialize, CanonicalDeserialize)]
pub struct MuSig2Signature<G: AffineRepr> {
    /// The aggregated nonce point
    pub r: G,

    /// The aggregated signature scalar
    pub s: G::ScalarField,
}

impl<G: AffineRepr> MuSig2Signature<G> {
    /// Creates a new MuSig2 signature
    pub fn new(r: G, s: G::ScalarField) -> Self {
        Self { r, s }
    }

    /// Converts the signature to a tuple
    pub fn to_tuple(&self) -> (G, G::ScalarField) {
        (self.r, self.s)
    }

    /// Creates a signature from a tuple
    pub fn from_tuple(tuple: (G, G::ScalarField)) -> Self {
        Self {
            r: tuple.0,
            s: tuple.1,
        }
    }
}
